checkpoint:
  # model_type: vit_b
  # path: "./storage/model_zoo/sam/sam_vit_b_01ec64.pth"
  model_type: vit_b
  path: "./storage/model_zoo/sam/sam_vit_b_01ec64.pth"

model:
  num_queries: 64
  points_per_side: 8
  points_per_batch: 64

fine_tune:
  image_encoder: False
  mask_decoder: False
